name: wakel
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  google_fonts:
  flutter_swiper: ^1.1.6
  carousel_slider: ^2.3.1
  liquid_progress_indicator: ^0.3.2
  shared_preferences:
  popup_menu: ^1.0.5
  custom_switch: ^0.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      - assets/images/logosplash.png
      - assets/images/wakel.png
      - assets/images/profile.png
      - assets/images/question.png
      - assets/images/twi.png
      - assets/images/chatp.png
      - assets/images/truew.png
      - assets/images/insta.png
      - assets/images/like.png
      - assets/images/dislike.png
      - assets/images/idimg.png
      - assets/images/jam.png
      - assets/images/book.png
      - assets/images/grafic.png
      - assets/images/tar.png
      - assets/images/khho.png
      - assets/images/prog.png

      - assets/images/google.png
      - assets/images/facebook.png
      - assets/images/person.png
      - assets/images/freelan.png
      - assets/images/imggirl.png
      - assets/images/zaka.png
      - assets/images/retry.png
      - assets/images/arrowd.png
      - assets/images/addimg.png
      - assets/images/gi.png
      - assets/images/mob.png
      - assets/images/sud.png
      - assets/images/noti.png
      - assets/images/waz.png
      - assets/images/back.png
      - assets/images/face.png
      - assets/images/googlep.png
      - assets/images/ppp.png
      - assets/images/hhh.png
      - assets/images/logon.png

      - assets/images/wazes.png
      - assets/images/jawaz.png
      - assets/images/maw.png
      - assets/images/social.png
      - assets/images/chat.png
      - assets/images/project.png
      - assets/images/pro.png
      - assets/images/home.png
      - assets/images/chati.png
      - assets/images/chatb.png
      - assets/images/chatg.png
      - assets/images/iconb.png
      - assets/images/bookmark.png
      - assets/images/dis.png

      - assets/images/sendicon.png
      - assets/images/tru.png
      - assets/images/attach.png
      - assets/images/sign.png
      - assets/images/audit.png
      - assets/images/msg.png
      - assets/images/chatmsg.png
      - assets/images/info.png
      - assets/images/card.png
      - assets/images/dollar.png
      - assets/images/visa.png
      - assets/images/paypal.png
      - assets/images/check.png
      - assets/images/truegreen.png
      - assets/images/mark.png
      - assets/images/trueblue.png
      - assets/images/girl.png
      - assets/images/inst.png
      - assets/images/menu.png
      - assets/images/timer.png
      - assets/images/doll.png
      - assets/images/cal.png
      - assets/images/cardNu.png
      - assets/images/cvct.png
      - assets/images/bankn.png
      - assets/images/quas.png
      - assets/images/proo.png
      - assets/images/prot.png
      - assets/images/proth.png
      - assets/images/file.png
      - assets/images/absher.png
      - assets/images/adel.png
      - assets/images/revmsg.png
      - assets/images/sendmsg.png
      - assets/images/scoc.png
      - assets/images/dog.png
      - assets/images/send.png
      - assets/images/stop.png
      - assets/images/price.png
      - assets/images/flags.png
      - assets/images/mute.png
      - assets/images/tile.png
      - assets/images/gender.png
      - assets/images/age.png
      - assets/images/baby.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  fonts:
    - family: Cairo-Black
      fonts:
          - asset: assets/fonts/Cairo-Black.ttf
    - family: Cairo-Bold
      fonts:
          - asset: assets/fonts/Cairo-Bold.ttf
    - family: Cairo-SemiBold
      fonts:
          - asset: assets/fonts/Cairo-SemiBold.ttf
    - family: Cairo-Regular
      fonts:
          - asset: assets/fonts/Cairo-Regular.ttf
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
